### ISSUE TITLE
Bug in RGBBytes function

### ISSUE THREAD

**Issue by MrMajestic1** [xyproto/tinysvg#1]
There's a bug on line 242 in [`tinysvg.go`](https://github.com/xyproto/tinysvg/blob/a621ad8949c346ab3f38db836708621c21b9173f/tinysvg.go#L242). It uses then incoming green value to produce bytes for the blue component. 
Now (note the `g` passed as argument to `int64`):
```
bs := strconv.FormatInt(int64(g), 16)
```
should be:
```
bs := strconv.FormatInt(int64(b), 16)
```

I've submitted a pull request fixing it.

**Comment by xyproto** [comment]
Thank you! Merged.
